import React, { useState, useEffect } from 'react';
import { 
  Wallet, 
  Download, 
  FileText,
  Printer
} from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export default function MyPayslips() {
  const { user } = useAuth();
  const [payrollRuns, setPayrollRuns] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchPayroll = async () => {
      try {
        const res = await fetch('/api/hr/payroll');
        if (res.ok) {
          const data = await res.json();
          // Filter or map payroll records matching our demo period
          setPayrollRuns(data);
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    fetchPayroll();
  }, []);

  const handlePrintMock = () => {
    window.print();
  };

  if (loading) {
    return (
      <div className="flex h-full items-center justify-center p-12">
        <div className="w-10 h-10 border-4 border-teal-200 border-t-teal-600 rounded-full animate-spin"></div>
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto space-y-8 pb-12">
      {/* Page Header */}
      <div className="flex justify-between items-center bg-white p-6 rounded-3xl border border-slate-100 shadow-sm">
        <div>
          <h1 className="text-3xl font-black text-slate-800 tracking-tight">My Payslips</h1>
          <p className="text-slate-500 font-medium mt-1">Access and print payroll slips generated by the Finance team.</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Payroll History List */}
        <div className="bg-white rounded-3xl p-8 border border-slate-100 shadow-sm lg:col-span-2 space-y-6">
          <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2 border-b border-slate-100 pb-4">
            <Wallet className="text-teal-600" size={20} /> Generated Payslips
          </h2>

          <div className="divide-y divide-slate-100">
            {payrollRuns.length > 0 ? (
              payrollRuns.map((run, idx) => (
                <div key={idx} className="py-4 flex justify-between items-center first:pt-0 last:pb-0">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-slate-50 rounded-xl flex items-center justify-center text-slate-400">
                      <FileText size={20} />
                    </div>
                    <div>
                      <p className="font-bold text-slate-800 text-sm">Salary Statement — {run.period || 'July 2026'}</p>
                      <p className="text-xs text-slate-400 font-semibold">Processed on {new Date(run.createdAt).toLocaleDateString()}</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <button 
                      onClick={handlePrintMock}
                      className="p-2.5 bg-slate-50 hover:bg-slate-100 rounded-xl text-slate-600 transition-colors"
                      title="Print Payslip"
                    >
                      <Printer size={16} />
                    </button>
                    <button 
                      onClick={() => alert('Downloading payslip PDF...')}
                      className="p-2.5 bg-teal-50 hover:bg-teal-100 rounded-xl text-teal-600 transition-colors"
                      title="Download PDF"
                    >
                      <Download size={16} />
                    </button>
                  </div>
                </div>
              ))
            ) : (
              // Structured fallbacks for immediate visibility
              ['June 2026', 'May 2026', 'April 2026'].map((period, idx) => (
                <div key={idx} className="py-4 flex justify-between items-center first:pt-0 last:pb-0">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 bg-slate-50 rounded-xl flex items-center justify-center text-slate-400">
                      <FileText size={20} />
                    </div>
                    <div>
                      <p className="font-bold text-slate-800 text-sm">Salary Statement — {period}</p>
                      <p className="text-xs text-slate-400 font-semibold">Verified & Disbursed</p>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <button 
                      onClick={handlePrintMock}
                      className="p-2.5 bg-slate-50 hover:bg-slate-100 rounded-xl text-slate-600 transition-colors"
                    >
                      <Printer size={16} />
                    </button>
                    <button 
                      onClick={() => alert('Downloading payslip PDF...')}
                      className="p-2.5 bg-teal-50 hover:bg-teal-100 text-teal-650 rounded-xl text-teal-600 transition-colors"
                    >
                      <Download size={16} />
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        </div>

        {/* Finance notice info card */}
        <div className="bg-slate-900 text-white rounded-3xl p-8 flex flex-col justify-between">
          <div className="space-y-4">
            <span className="bg-teal-500/10 text-teal-400 text-xs font-bold px-3 py-1.5 rounded-full border border-teal-500/20">
              Tax & Deductions
            </span>
            <h2 className="text-xl font-bold">Income Tax Declarations</h2>
            <p className="text-slate-400 text-sm leading-relaxed">
              Ensure you upload your Form 12BB tax declarations before the end of the quarter to prevent excessive TDS deductions.
            </p>
          </div>
          <div className="border-t border-slate-800 pt-6 mt-8">
            <p className="text-xs text-slate-500">Need adjustments? Contact finance department.</p>
          </div>
        </div>
      </div>
    </div>
  );
}
